#!/usr/bin/env sh
# This file is part of heroku-skeleton-buildpack. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/heroku-skeleton-buildpack/master/COPYRIGHT. No part of heroku-skeleton, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2015 The developers of heroku-skeleton-buildpack. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/heroku-skeleton-buildpack/master/COPYRIGHT.


_program()
{
	core_usesIn heroku
	core_usesIn heroku validate configure
    heroku_deploy()
    {
		heroku_configure_initialise
		heroku_configure_register
		heroku_configure_load
		
		heroku_findBuildPackUrl
		heroku_createAppIfNecessary
		heroku_setEnvironmentVariables
		heroku_deploy
    }
}

_program_name='deploy'
_program_namespace='heroku_deploy'
_program_version='unversioned'
_program_package_or_build=''
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_varPath="${_program_path}/var"
_program_entrypoint='heroku_deploy'

_program_commandLine_parseInitialise()
{
	heroku_repository_default="$(pwd)"
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="[OPTION]...
"
	_program_commandLine_helpMessage_description="Deploys Heroku apps, optionally creating them"
	_program_commandLine_helpMessage_options="
  -r, --repository PATH  PATH to a Git repository (or a subfolder in it).
                         Defaults to '$heroku_region_default'."
    _program_commandLine_helpMessage_optionsSpacing='   '
	_program_commandLine_helpMessage_configurationKeys="
  heroku_repository      Equivalent to --repository
"
	_program_commandLine_helpMessage_examples="
  ${_program_name} -r /path/to/folder/containing/.git
"
}

_program_commandLine_optionExists()
{
	case "$optionName" in
		
		r|repository)
			echo 'yes-argumented'
		;;
		
		*)
			echo 'no'
		;;
		
	esac
}

_program_commandLine_processOptionWithArgument()
{
	case "$optionName" in
		
		r|repository)
			heroku_validate_repositoryPathAndSetVariable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			#heroku_repositoryPath is set by the above function
			heroku_repository="$optionValue"
		;;
		
	esac
}

_program_commandLine_validate()
{
	if core_variable_isUnset heroku_repository; then
		heroku_repository="$heroku_repository_default"
		heroku_validate_repositoryPathAndSetVariable $core_commandLine_exitCode_CONFIG 'default' 'heroku_repository_default' "$heroku_repository_default"
		#heroku_repositoryPath is set by the above function
	else
		heroku_validate_repositoryPathAndSetVariable $core_commandLine_exitCode_CONFIG 'configuration setting' 'heroku_repository' "$heroku_repository"
		#heroku_repositoryPath is set by the above function
	fi
}

. "$_program_libPath"/shellfire/core/init.functions "$@"
