#!/usr/bin/env sh
# This file is part of heroku-skeleton-buildpack. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/heroku-skeleton-buildpack/master/COPYRIGHT. No part of heroku-skeleton, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2015 The developers of heroku-skeleton-buildpack. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/heroku-skeleton-buildpack/master/COPYRIGHT.


_program()
{
	core_usesIn heroku
	core_usesIn heroku validate buildpack
    heroku_detect()
    {
		local heroku_configurationFolderPath="$heroku_buildpack_buildDir"/"$heroku_configurationFolderName"
		if ! core_path_isReadableAndSearchableFolderPath "$heroku_configurationFolderPath"; then
			core_exitError $core_commandLine_exitCode_FAILURE "There is no heroku configuration folder '$heroku_configurationFolderName' in BUILD_DIR '$heroku_buildpack_buildDir'"
		fi
		
		local heroku_buildpacksConfigurationFolderPath="$heroku_configurationFolderPath"/"$heroku_buildpacksConfigurationFolderName"
		if ! core_path_isReadableAndSearchableFolderPath "$heroku_configurationFolderPath"; then
			core_exitError $core_commandLine_exitCode_FAILURE "There is no heroku buildpacks configuration folder '$heroku_buildpacksConfigurationFolderName' in BUILD_DIR/$heroku_configurationFolderName '$heroku_configurationFolderPath'"
		fi
		
		# Interferes with https://elements.heroku.com/buildpacks/jessefulton/buildpack-procfile-select
		#local procfilePath="$heroku_buildpacksConfigurationFolderPath"/Procfile
		#if ! core_path_isReadableFilePath "$procfilePath"; then
		#	core_exitError $core_commandLine_exitCode_FAILURE "There is no heroku 'Procfile' in configuration folder path '$heroku_buildpacksConfigurationFolderPath'"
		#fi
		
		# We take over from https://github.com/heroku/heroku-buildpack-multi
		local buildpacksFilePath="$heroku_buildpacksConfigurationFolderPath"/.buildpacks
		if ! core_path_isReadableFilePath "$buildpacksFilePath"; then
			core_exitError $core_commandLine_exitCode_FAILURE "There is no heroku '.buildpacks' in configuration folder path '$heroku_buildpacksConfigurationFolderPath'"
		fi
		
		printf '%s\n' "$heroku_frameworkName"
		exit $core_commandLine_exitCode_OK
    }
}

_program_name='detect'
_program_namespace='heroku_detect'
_program_version='unversioned'
_program_package_or_build=''
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_varPath="${_program_path}/var"
_program_entrypoint='heroku_detect'

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="BUILD_DIR
"
	_program_commandLine_helpMessage_description="Detects if this Heroku buildpack is appropriate for a Heroku app"
	_program_commandLine_helpMessage_options=""
    _program_commandLine_helpMessage_optionsSpacing='   '
	_program_commandLine_helpMessage_configurationKeys=""
	_program_commandLine_helpMessage_examples="
  ${_program_name} BUILD_DIR
"
}

_program_commandLine_parse()
{
	heroku_validate_buildDirCommandLineParse "$@"
}

. "$_program_libPath"/shellfire/core/init.functions "$@"
