#!/usr/bin/env sh
# This file is part of heroku-skeleton-buildpack. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/heroku-skeleton-buildpack/master/COPYRIGHT. No part of heroku-skeleton, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2015 The developers of heroku-skeleton-buildpack. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/heroku-skeleton-buildpack/master/COPYRIGHT.


cat <<EOF
---
default_process_types:
  web: gem server -d ./gems_home -p \$PORT --no-daemon
EOF

# TODO: THIS CODE DOESNT WORK!
# We need a whitelist of what to keep, otherwise it goes...
#rm -rf "$BUILD_DIR"/heroku 1>out
#rm "$BUILD_DIR"/Procfile 1>>out
#rm "$BUILD_DIR"/bin 1>>out
#rm "$BUILD_DIR"/deploy-to-heroku 1>>out
#rm "$BUILD_DIR"/README.md 1>>out

exit 0
